fix: invoke source map
midwayjs/midway-faas pull request #52
Opened 2020-02-19 07:41 UTC by echosoar

+ 修复invoke时sourceMap的root路径问题
+ faas-cli 无命令时显示帮助
+ faas 有个边界问题

2020-02-19 07:44 UTC, czy88840616 commented on packages/faas-cli-plugin-invoke/src/index.ts
> +        process.exit();
那catch这里也要 exit(1) 吧

2020-02-19 07:45 UTC, echosoar commented on packages/faas-cli-plugin-invoke/src/index.ts
> +        process.exit();
有道理

2020-02-20 14:52 UTC, Lxxyx approved these changes

2020-02-20 15:14 UTC, czy88840616 requested changes

2020-02-20 15:14 UTC, czy88840616 commented on packages/faas-cli-plugin-package/src/index.ts
> +          source: resolve(this.servicePath, 'src'),
这里原来好像允许改的。。这样岂不是不能了么。。

2020-02-20 15:14 UTC, czy88840616 commented on packages/faas-cli-plugin-package/src/index.ts
> +          sourceDir: resolve(this.servicePath, 'src'),
这里可能也是

2020-02-20 15:14 UTC, czy88840616 commented on packages/faas-util-ts-compile/src/index.ts
> +      tsConfig.compilerOptions.tsBuildInfoFile = resolve(baseDir, '.tsbuildinfo');
这里我觉得有点问题。。。`. tsbuildinfo` 文件应该不能在根目录，得在build目录，不然不会被清理，一直被增量。

2020-02-20 15:14 UTC, czy88840616 commented on packages/serverless-invoke/src/core.ts
>        // TODO 重构 midway-bin 不生成 tsconfig
这个TODO 可以去掉了。 。。

2020-02-20 15:14 UTC, czy88840616 commented on packages/serverless-invoke/src/core.ts
> +        source: resolve(baseDir, 'src'),
总觉得这里应该读传相对路径，要绝对路径也只在最底层处理

2020-02-20 16:05 UTC, legendecas approved these changes

2020-02-20 16:14 UTC, Lellansin approved these changes

2020-02-21 05:09 UTC, czy88840616 approved these changes

2020-02-21 05:09 UTC, merged